name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: windows-latest  # Use the Windows runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK (if necessary)
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Specify your Java version if you're working with a Java project

      - name: Verify Sonar Scanner Path
        run: |
          # Check if sonar-scanner is available in the PATH
          sonar-scanner --version

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: sqp_26abc256d0dafb51ec58afa086a98a8bab04ff27  # Use the token stored as a secret
        run: |
          sonar-scanner ^
            -Dsonar.projectKey=your_project_key ^
            -Dsonar.projectName="Your Project Name" ^
            -Dsonar.projectVersion=1.0 ^
            -Dsonar.sources=src ^
            -Dsonar.host.url=https://your-sonarqube-server.com ^
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
