name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: windows-latest  # Use the Windows runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK (if necessary)
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify your Java version if you're working with a Java project

      - name: Install Sonar Scanner
        run: |
          # Download and install Sonar Scanner
          Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-windows.zip" -OutFile "sonar-scanner.zip"
          Expand-Archive -Path "sonar-scanner.zip" -DestinationPath "C:\sonar-scanner" -Force
          # Add Sonar Scanner to the PATH
          $env:Path += ";C:\sonar-scanner\sonar-scanner-4.8.0.2856-windows\bin"

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Use the token stored as a secret
        run: |
          sonar-scanner ^
            -Dsonar.projectKey=your_project_key ^
            -Dsonar.projectName="Your Project Name" ^
            -Dsonar.projectVersion=1.0 ^
            -Dsonar.sources=src ^
            -Dsonar.host.url=https://your-sonarqube-server.com ^
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
